export type Quotation = {
  id: number;
  customer_id: number;
  customer_name?: string;
  customer_email?: string;
  request_date: string;
  insurance_type: number;
  bonus_class: string | null;
  has_claims: number | null;
  vehicle_plate: string;
  vehicle_chassis: string;
  vehicle_brand: string;
  vehicle_model: string;
  manufacture_year: number;
  overnight_zipcode: string;
  driver_age: number;
  license_time: string;
  coverages: string[] | string | null;
  has_insurer_preference: number;
  preferred_insurer: string | null;
  active: number;
};
