name: Deploy Production

on:
  push:
    branches:
      - master

jobs:
  deploy-prod:
    name: Deploy produção
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na VM via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            set -e

            cd ~/projects/cotacao/prod

            git fetch origin
            git checkout master
            git reset --hard origin/master

            cp .env.prod.example .env

            docker compose up -d --build --remove-orphans

            docker image prune -f